### PR TITLE
mlx5: always leave one free slot in rx ring

### PR DESCRIPTION
**Pull request by driesdewinter**
Previously mlx5e_netmap_rxsync() could completely fill up the rx ring but
user space cannot tell the difference between empty and completely full, so
it would be considered as empty and the ring would be stuck forever.

This is now avoided by never making more than (ring size - 1) buffer slots
available for packet reception.

### CODE REVIEW

**Comment by kierank** [comment]
@JDarnley When you have a chance can you test this on our side. 
I don't think we ever reach empty/full though

**Comment by JDarnley** [comment]
I've been using this commit today and I haven't seen any problems or changes in how the RX on the nic behaves.  But as we've said we probably don't reach full because we are ready to handle RX before we get any packets.

**Comment by giuseppelettieri** [comment]
The commit is consistent with what we do with the other drivers, so I am going to merge it if there are no objections. Thanks!

**Comment by driesdewinter** [comment]
Friendly reminder: I see no objections, so it can be merged in then?

**Comment by giuseppelettieri** [comment]
Yep, merged. Thanks!

**Pull request merged**
