### PR TITLE
Make VLAN tags visible to Linux generic adapter

### PR DESCRIPTION
**Pull request by msaare123**
Push tag in skb metadata back to payload so it will be visible in rx ring

### CODE REVIEW

**Comment by vmaffione** [comment]
Looks like a good idea, but we would need to check that it compiles for all the earlier versions on Linux. @giuseppelettieri ?

**Comment by msaare123** [comment]
> Looks like a good idea, but we would need to check that it compiles for all the earlier versions on Linux. @giuseppelettieri ?

What is range of supported kernels? With quick glance this should be compatible from v4.x kernels.

**Comment by vmaffione** [comment]
We actually support Linux since 2.6.34.

The configure script `LINUX/configure` has many tests to check for internal kernel functions and signatures. The script will produce a `netmap_linux_config.h` with all the #define that allow the code to support many versions.
Then there is a `LINUX/scripts/np` that automates the build across all the possible versions, but it's not so easy to setup.

**Comment by giuseppelettieri** [comment]
> We actually support Linux since 2.6.34.

yes, we do, but we should really stop doing that. Anyway, I'll check compilation and report back.

**Comment by giuseppelettieri** [comment]
OK, we can merge this. Then I will push some commits that will fix compilation for all kernels. For very old kernels, however, the vlan feature will simply be disabled, since emulating the missing pieces becomes too cumbersome.

**Pull request merged**
