### PR TITLE
Added log levels for printf function as in linux.

### PR DESCRIPTION
**Pull request by spinenkoia**
https://github.com/luigirizzo/netmap/issues/303

### CODE REVIEW

**Comment by vmaffione** [comment]
A patch in this direction is very welcome, thanks.
But this is not the approach we are looking for, we don't want to inherit Linux KERN_** macros.
We would like to have two macros, one to print errors and one to print info, e.g.,
````
  nm_prerr("error message %d", xxx)
  nm_prinf("info message %d", xxx)
````
On Linux nm_prerr maps to printk(KERN_ERR) and nm_prinf maps to printk(KERN_INFO).
On FreeBSD both can map to printf().
Could you please align your patch in this direction?

**Comment by spinenkoia** [comment]
Yes OK.
Did I understand correctly that instead of a single function, do you need to use nm_prrr and nm_printer?

**Comment by vmaffione** [comment]
Yes, netmap code will use one function or the other depending on the specific needs.

**Comment by spinenkoia** [comment]
@vmaffione Look please that it turned out, is such a decision satisfied?

**Comment by vmaffione** [comment]
It looks good, but we need to check if compilation is ok on FreeBSD. Have you checked it by any chance?

**Comment by spinenkoia** [comment]
FreeBSD has not yet been tested, only in Linux. In the near future I will check.

**Comment by vmaffione** [comment]
Thanks. I've checked on FreeBSD, it is ok.
Next step would be to get rid of the D,ND and RD macros and use nm_prinf and nm_prerr everywhere.

**Comment by spinenkoia** [comment]
Yes, I think I will do it. It would also be useful for me.

**Comment by vmaffione** [comment]
Sounds good! Actually, we can leave ND macros (they result into nothing), and we need another nm_prlim() macro to replace RD.

**Comment by spinenkoia** [comment]
Okay, I'll keep that in mind.

**Pull request merged**
